version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [housekeeping, dependencies]
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: npm
    directories: ["/", "/site"]
    schedule:
      interval: weekly
    labels: [housekeeping, dependencies]
    groups:
      npm:
        patterns: ["*"]
